# Generated by Django 4.1.7 on 2023-04-16 17:07

import api.catalog.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категорія')),
                ('title', models.BooleanField(blank=True, null=True, verbose_name='Це заголовок підкатегорії?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': "'Категорії",
                'verbose_name_plural': 'Категорія',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Матеріала')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріал',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Назва товару')),
                ('poster', models.ImageField(upload_to=api.catalog.models.get_poster_path, verbose_name='Постер продукту')),
                ('quantity', models.IntegerField(verbose_name='Кількість товару на складі')),
                ('price', models.IntegerField(verbose_name='Ціна товару')),
                ('characters', models.JSONField(blank=True, null=True, verbose_name='Додаткові характеристики товару')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField(verbose_name='Опис товару')),
                ('categories', models.ManyToManyField(to='catalog.category', verbose_name='Категорія')),
                ('materials', models.ManyToManyField(to='catalog.material', verbose_name='Матеріал')),
            ],
            options={
                'verbose_name': 'Товари',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=api.catalog.models.get_photos_path, verbose_name='Фотографія')),
                ('product', models.ForeignKey(help_text='Продукт, якому належить фотографія.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фотографія продукту',
                'verbose_name_plural': 'Фотографії продукту',
            },
        ),
    ]
