# Generated by Django 4.1.7 on 2023-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='disadvatages',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Недоліки'),
        ),
    ]
