# Generated by Django 4.1.7 on 2023-06-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_comments_disadvatages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='advatages',
            new_name='advantages',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='disadvatages',
            new_name='disadvantages',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='text',
        ),
    ]
