# Generated by Django 4.1.7 on 2023-06-19 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_alter_comments_product_alter_comments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кількість товару')),
                ('price', models.IntegerField(verbose_name='Ціна товару')),
                ('total_price', models.IntegerField(verbose_name='Загальна ціна')),
                ('info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
